version: '3'
services:
    postgres:
      container_name: postgres
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        PGDATA: /Users/shikma/postgres_volum
      ports:
        - "5432:5432"
    adminer:
      image: adminer
      ports:
        - "8080:8080"