version: '3'
services:
    postgres:
      container_name: postgres
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
    adminer:
      image: adminer
      ports:
        - "8080:8080"
    nestjs-server:
      build:
        context: ./server
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      container_name: nest-api
    next-frontend:
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
      - "3000:3000"
      container_name: transcendence-frontend