version: '3'
services:
    postgres:
      container_name: postgres
      image: postgres:latest
      restart: always
      env_file:
        - ./server/.env
      # environment:
      #   POSTGRES_USER: ${POSTGRES_USER}
      #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #   POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
    adminer:
      image: adminer
      ports:
        - "8080:8080"